version: "3.8"

volumes:
    postgres-data:

services:
    db:
        container_name: postgresdb
        image: postgres:17
        restart: unless-stopped

        ports:
            - "5432:5432"

        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOSTNAME: postgresdb

        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./database-altave.sql:/docker-entrypoint-initdb.d/database-altave.sql
